import { SiteConfig } from "@/types";

/**
 * Default Site Configuration for $99 Tint Club Detailing
 * 
 * NOTE: Factual business figures (vehicle counts, location details, warranties,
 * and client testimonials) are structured here for convenient updating by the owner.
 * Any unverified metrics are clearly labeled for client confirmation.
 */

export const initialSiteConfig: SiteConfig = {
  brandName: "$99 TINT CLUB",
  tagline: "Ultra Bespoke Automotive Care & Protection",
  heroBadge: "Bespoke Motorsport Detailing Lab",
  heroTitleLine1: "PERFECTION",
  heroTitleHighlight: "RE-ENGINEERED",
  heroTitleLine2: "FOR HYPERCARS & LUXURY",
  heroDescription:
    "Elevating automotive elegance through precision ceramic coatings, premium self-healing PPF, and multi-stage optical paint restoration in a controlled environment.",
  phone: "+1 (909) 790-9988",
  email: "concierge@99tintclub.com",
  address: "34800 Yucaipa Blvd, Yucaipa, CA 92399 (Serving the Inland Empire)",
  workingHours: "Mon - Sat: 8:00 AM - 6:00 PM",
  emergencyHotline: "+1 (800) 998-3824",
  heroSupercarImage: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=1600&auto=format&fit=crop",
  theme: {
    accent: "apex-combo",
    fontSize: "normal",
    enableGridBackground: true,
    enableAmbientGlow: true,
    cardGlassOpacity: 65,
  },
  // Simplified primary navigation per requirements
  navItems: [
    { id: "1", label: "Home", href: "#hero", order: 1, isVisible: true },
    { id: "2", label: "Services", href: "#services", order: 2, isVisible: true },
    { id: "3", label: "Projects", href: "#projects", order: 3, isVisible: true },
    { id: "4", label: "About", href: "#about", order: 4, isVisible: true },
    { id: "5", label: "Reviews", href: "#reviews", order: 5, isVisible: true },
    { id: "6", label: "Contact", href: "#contact", order: 6, isVisible: true },
  ],
  // Standardized business stats (pending final client verification)
  stats: [
    { id: "s1", label: "Vehicles Enhanced", value: "1,500", suffix: "+", description: "Supercars, sports & luxury models serviced" },
    { id: "s2", label: "Installation Bays", value: "Precision", suffix: " Lab", description: "Climate-controlled, dust-filtered environment" },
    { id: "s3", label: "Optical Clarity", value: "99+", suffix: " GU", description: "High-gloss specular reflectance index" },
    { id: "s4", label: "Client Satisfaction", value: "99", suffix: "%", description: "Private collector and enthusiast referrals" },
  ],
  services: [
    {
      id: "srv-wt-1",
      title: "Automotive Window Tinting",
      subtitle: "Comfort, Clarity & UV Defense",
      category: "Window Tinting",
      duration: "2-3 Hours",
      popular: true,
      badge: "Most Popular",
      description:
        "Enhance driving comfort and privacy with professionally installed window tint that reduces glare and UV exposure.",
      image: "https://images.unsplash.com/photo-1617814076367-b759c7d7e738?q=80&w=1200&auto=format&fit=crop",
      features: [
        "Reduces Driving Heat & Harsh Sun Glare",
        "Blocks 99% Harmful UV Rays",
        "Protects Interior Upholstery From Fading",
        "Computer-Cut Precision Fitment",
        "Factory-Style Sleek Appearance",
      ],
    },
    {
      id: "srv-wt-2",
      title: "Residential Window Tinting",
      subtitle: "Home Comfort & Energy Reduction",
      category: "Window Tinting",
      duration: "Scheduled Bay",
      popular: false,
      badge: "Home Solar Shield",
      description:
        "Make your home more comfortable with window film that reduces solar heat, softens glare, and helps limit fading of interior furnishings.",
      image: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=1200&auto=format&fit=crop",
      features: [
        "Lowers Home Cooling & AC Energy Bills",
        "Softens Blinding Glare Through Living Areas",
        "Protects Hardwood Flooring & Valued Art",
        "Retains Natural Daylight & Exterior Vista",
        "Shatter-Resistant Glass Safety Factor",
      ],
    },
    {
      id: "srv-wt-3",
      title: "Commercial Window Tinting",
      subtitle: "Workplace & Storefront Solar Control",
      category: "Window Tinting",
      duration: "Scheduled Bay",
      popular: false,
      badge: "Commercial Grade",
      description:
        "Improve comfort in offices, storefronts, and commercial buildings with solar-control films that reduce heat and screen glare.",
      image: "https://images.unsplash.com/photo-1486406146926-c627a92ad1ab?q=80&w=1200&auto=format&fit=crop",
      features: [
        "Reduces Commercial HVAC Operating Load",
        "Eliminates Computer Screen Reflection",
        "Elevates Tenant Comfort & Productivity",
        "Modern Architectural Uniform Exterior",
        "Enhanced Security & Impact Protection",
      ],
    },
    {
      id: "srv-wt-4",
      title: "Ceramic Window Tint",
      subtitle: "Maximum Infrared Heat Rejection",
      category: "Window Tinting",
      duration: "3-4 Hours",
      popular: true,
      badge: "Flagship Nano-Ceramic",
      description:
        "Upgrade your vehicle with ceramic window film for enhanced heat rejection, UV protection, and clear visibility.",
      image: "https://images.unsplash.com/photo-1503376780353-7e6692767b70?q=80&w=1200&auto=format&fit=crop",
      features: [
        "Supreme Infrared (IR) Heat Rejection",
        "Non-Metallic: Zero GPS or Mobile Interference",
        "High Optical Clarity Night & Day",
        "Maximum Total Solar Energy Rejected (TSER)",
        "Lifetime Color-Stable Manufacturer Warranty",
      ],
    },
    {
      id: "srv-wt-5",
      title: "Privacy & Decorative Window Film",
      subtitle: "Frosted Glass & Architectural Partitions",
      category: "Window Tinting",
      duration: "Custom Project",
      popular: false,
      badge: "Architectural",
      description:
        "Create privacy with frosted and decorative films for home windows, office partitions, conference rooms, and storefronts.",
      image: "https://images.unsplash.com/photo-1497366216548-37526070297c?q=80&w=1200&auto=format&fit=crop",
      features: [
        "Frosted, Matte & Patterned Glass Finishes",
        "Conference Room & Restroom Privacy",
        "Custom Cut Graphic Logos & Banding",
        "Diffuses Direct Light Without Darkening Rooms",
        "Removable & Easy to Maintain",
      ],
    },
    {
      id: "srv-wt-6",
      title: "Window Tint Removal & Replacement",
      subtitle: "Defective Tint Strip & Clean Replacement",
      category: "Window Tinting",
      duration: "2-4 Hours",
      popular: false,
      badge: "Clean Restoration",
      description:
        "Refresh faded, bubbling, or peeling tint with professional removal and replacement for a clean finish and improved performance.",
      image: "https://images.unsplash.com/photo-1552519507-da3b142c6e3d?q=80&w=1200&auto=format&fit=crop",
      features: [
        "Safe Steam & Chemical Adhesive Dissolution",
        "Full Protection for Rear Defroster Filaments",
        "Eliminates Purple, Hazy, and Bubbled Film",
        "Deep Surface Decontamination & Prep",
        "Fresh Premium Replacement Application",
      ],
    },
    {
      id: "srv-ppf-1",
      title: "Self-Healing PPF Stealth Armor",
      subtitle: "Ultimate Road Surface Defense",
      category: "Paint Protection (PPF)",
      duration: "2-3 Days",
      popular: true,
      badge: "Track-Proven",
      description:
        "Engineered 10-mil aliphatic polyurethane shield that absorbs rock chips, stone abrasions, and road debris with continuous self-healing properties.",
      image: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=1200&auto=format&fit=crop",
      features: [
        "10-Mil Hydrophobic Polyurethane",
        "Instant Heat-Activated Self-Healing",
        "Optically Invisible Edge-Wrapped Fit",
        "10-Year Anti-Yellowing Warranty",
      ],
    },
    {
      id: "srv-cer-1",
      title: "Graphene & Ceramic Matrix Shield",
      subtitle: "Hyper-Hydrophobic Surface Matrix",
      category: "Ceramic Coating",
      duration: "1-2 Days",
      popular: false,
      badge: "Signature Shield",
      description:
        "Molecular covalent bonding formula yielding 10H pencil hardness with extreme contact angles for self-cleaning properties.",
      image: "https://images.unsplash.com/photo-1520340356584-f9917d1eea6f?q=80&w=1200&auto=format&fit=crop",
      features: [
        "10H Pencil Hardness Quartz Layer",
        "Extreme Water Beading Contact Angle",
        "Chemical & Bird Dropping Resistance",
        "5-Year Certified Warranty",
      ],
    },
    {
      id: "srv-cor-1",
      title: "Multi-Stage Paint Restoration",
      subtitle: "Optical Compounding & Polishing",
      category: "Paint Correction",
      duration: "8-12 Hours",
      popular: false,
      badge: "Optical Perfection",
      description:
        "Micro-measurement clear coat levelling eliminating up to 95% of wash swirls, micro-scratches, and holograms for true specular reflection.",
      image: "https://images.unsplash.com/photo-1607860108855-64acf2078ed9?q=80&w=1200&auto=format&fit=crop",
      features: [
        "90%+ Swirl & Scratch Elimination",
        "Micron-Level Clear Coat Preservation",
        "Mirror-Reflection Gloss Enhancement",
        "Jeweling Finish Stage",
      ],
    },
  ],
  projects: [
    {
      id: "proj-1",
      title: "Porsche 911 GT3 RS in Shark Blue",
      category: "Porsche",
      carModel: "911 GT3 RS (992)",
      year: "2024",
      glossRating: "99.9 GU",
      treatment: "Full Body Self-Healing PPF + Ceramic Topcoat",
      image: "https://images.unsplash.com/photo-1614162692292-7ac56d7f7f1e?q=80&w=1200&auto=format&fit=crop",
      tags: ["Track Armor", "PPF", "Ceramic Coating", "Weissach"],
    },
    {
      id: "proj-2",
      title: "Ferrari F8 Tributo in Rosso Corsa",
      category: "Ferrari",
      carModel: "F8 Tributo V8 Bi-Turbo",
      year: "2023",
      glossRating: "99.7 GU",
      treatment: "Stage 2 Paint Correction & Ceramic Sealant",
      image: "https://images.unsplash.com/photo-1592198084033-aade902d1aae?q=80&w=1200&auto=format&fit=crop",
      tags: ["Paint Correction", "Liquid Mirror", "Rosso Corsa"],
    },
    {
      id: "proj-3",
      title: "Lamborghini Huracán STO Matte Verde",
      category: "Lamborghini",
      carModel: "Huracán STO",
      year: "2024",
      glossRating: "Satin Shield",
      treatment: "Full Stealth Satin PPF & Carbon Aero Ceramic",
      image: "https://images.unsplash.com/photo-1544829099-b9a0c07fad1a?q=80&w=1200&auto=format&fit=crop",
      tags: ["Stealth PPF", "V10 Squadra", "Carbon Treatment"],
    },
    {
      id: "proj-4",
      title: "Mercedes-AMG G63 in Obsidian Black",
      category: "Mercedes-AMG",
      carModel: "G63 Biturbo AMG",
      year: "2024",
      glossRating: "99.4 GU",
      treatment: "Full Front PPF + Multi-Stage Polish + Leather Ceramic",
      image: "https://images.unsplash.com/photo-1520050206274-a1ae44613e6d?q=80&w=1200&auto=format&fit=crop",
      tags: ["Ceramic Protection", "Black Edition", "Executive SUV"],
    },
    {
      id: "proj-5",
      title: "McLaren 720S Spider in Papaya Spark",
      category: "McLaren",
      carModel: "720S Spider",
      year: "2023",
      glossRating: "99.8 GU",
      treatment: "Full PPF Wrap & Infrared Ceramic Tinting",
      image: "https://images.unsplash.com/photo-1621135802920-133df287f89c?q=80&w=1200&auto=format&fit=crop",
      tags: ["Hypercar Care", "Ceramic Tint", "Papaya Pearl"],
    },
    {
      id: "proj-6",
      title: "BMW M4 Competition in Isle of Man Green",
      category: "BMW M",
      carModel: "M4 Competition xDrive",
      year: "2024",
      glossRating: "99.5 GU",
      treatment: "Two-Stage Paint Correction & Ceramic Matrix",
      image: "https://images.unsplash.com/photo-1555215695-3004980ad54e?q=80&w=1200&auto=format&fit=crop",
      tags: ["Ceramic Matrix", "M Power", "Paint Restoration"],
    },
  ],
  // Testimonial entries: clearly marked as demo templates awaiting verified client reviews
  testimonials: [
    {
      id: "t1",
      name: "Marcus Vance",
      role: "Porsche Club Member",
      car: "Porsche 911 GT3 RS",
      rating: 5,
      platform: "Google Review",
      verified: false, // marked false until verified by client
      comment:
        "The attention to detail at $99 Tint Club is exceptional. The PPF installation on my GT3 RS has seamlessly wrapped edges, and the paint correction gave the Shark Blue finish incredible depth. Very professional team.",
      avatar: "https://images.unsplash.com/photo-1534528741775-53994a69daeb?q=80&w=200&auto=format&fit=crop",
      date: "October 2024",
    },
    {
      id: "t2",
      name: "Sophia Rodriguez",
      role: "Verified Client",
      car: "Mercedes-AMG G63",
      rating: 5,
      platform: "Client Direct",
      verified: false, // marked false until verified by client
      comment:
        "$99 Tint Club arranged enclosed transport for my G63 and returned it in pristine condition. The ceramic coating makes regular maintenance effortless, and the gloss in sunlight is remarkable.",
      avatar: "https://images.unsplash.com/photo-1580489944761-15a19d654956?q=80&w=200&auto=format&fit=crop",
      date: "September 2024",
    },
    {
      id: "t3",
      name: "Alexander Sterling",
      role: "Track & Enthusiast Driver",
      car: "McLaren 720S",
      rating: 5,
      platform: "Google Review",
      verified: false, // marked false until verified by client
      comment:
        "Working with carbon fiber components and thin performance lacquers requires true expertise. The $99 Tint Club team treated my McLaren with surgical care and kept me updated with photos throughout the process.",
      avatar: "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?q=80&w=200&auto=format&fit=crop",
      date: "November 2024",
    },
  ],
};
